sonar.projectKey=Vaibhav5418_Leadgen
sonar.organization=vaibhav5418
sonar.sources=leadgen-backend/src,leadgen-frontend/src
sonar.tests=leadgen-backend/src/__tests__,leadgen-frontend/src/__tests__
sonar.javascript.lcov.reportPaths=leadgen-backend/coverage/lcov.info,leadgen-frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.cpd.exclusions=leadgen-backend/src/__tests__/**,leadgen-frontend/src/__tests__/**
